# ----------------------------
# Set NAME to the program name
# Set ICON to the png icon file name
# Set DESCRIPTION to display within a compatible shell
# Set COMPRESSED to "YES" to create a compressed program
# ----------------------------

NAME        ?= BOUNCE
COMPRESSED  ?= NO
ICON        ?= icon.png
DESCRIPTION ?= "C Physics Demo"

# ----------------------------
# Other Options (Advanced)
# ----------------------------

#EXTRA_CFLAGS        ?=
USE_FLASH_FUNCTIONS ?= NO
#OUTPUT_MAP          ?= YES|NO
#ARCHIVED            ?= YES|NO
OPT_MODE            ?= -optspeed
#SRCDIR              ?= src
#OBJDIR              ?= obj
#BINDIR              ?= bin
#GFXDIR              ?= src/gfx
#V                   ?= 1

include $(CEDEV)/include/.makefile
